### ISSUE TITLE
NoMethodError When Executing `bundle exec bake utopia:project:static`

### ISSUE THREAD

**Issue by aristotelesbr** [socketry/utopia-project#10]
I encountered a `NoMethodError` when running the command `bundle exec bake utopia:project:static`. This error prevents the completion of the command and affects the static generation of the project. The specific error indicates that the `project_title` method is undefined.

## Expected

When running the command `bundle exec bake utopia:project:static`, it was expected that the project would generate static files without any errors. Failure in this process prevents the completion of the task.

## Error

```bash
...
guides/index.html                     100%[=======================================================================>]   1,35K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2024-01-09 15:28:42 (1,28 GB/s) - ‘../lennarb/docs/guides/index.html’ saved [1379/1379]

--2024-01-09 15:28:42--  http://localhost:52040/guides/performance/static/r10k/build/lennarb.rb
Reusing existing connection to [localhost]:52040.
HTTP request sent, awaiting response... NoMethodError: undefined method `project_title' for nil (NoMethodError)
        /Users/aristoteles/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/utopia-project-0.23.0/pages/_header.xnode:11:in `public_send'
        /Users/aristoteles/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/utopia-project-0.23.0/pages/_header.xnode:11:in `block (2 levels) in <module:Trenni>'
        /Users/aristoteles/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/utopia-2.23.0/lib/utopia/path.rb:291:in `block in descend'
        /Users/aristoteles/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/utopia-2.23.0/lib/utopia/path.rb:288:in `each'
        /Users/aristoteles/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/utopia-2.23.0/lib/utopia/path.rb:288:in `descend'
        /Users/aristoteles/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/utopia-project-0.23.0/pages/_header.xnode:4:in `block in <module:Trenni>'
```

More details:

https://github.com/aristotelesbr/lennarb/actions/runs/7464779667/job/20312490293#step:5:438

Use ruby 3.3.0. All dependencies 👉 [here](https://github.com/aristotelesbr/lennarb/blob/main/gems.rb)

Thanks for the project, folks! Really appreciate it!

**Comment by ioquatix** [comment]
The problem is the link to the benchmark code. Unfortunately, there is currently no easy way to embed code like this (or link to it). Maybe in the future we will add such a feature, but for now I think my advice is to show the commands to execute the benchmark, e.g. instead of linking to the benchmark, show how to run it (and additionally move it from `static/` to `benchmark/` or something like that).

**Comment by aristotelesbr** [comment]
Thanks for the tip about the benchmark code. Your suggestion was very useful and I am already implementing it. 😁

**Comment by aristotelesbr** [comment]
All done!

Tks! 😁
